### ISSUE TITLE
Revisión documentos de requisitos

### ISSUE THREAD

**Issue by joaquinballesteros** [JavierSantiburcio/Proyecto-Sporter#2]
3.3 Interfaces con el Software, introducir si teneís versiónes de BD o lenguaje mínimas para usar.

Primero va la tabla de precedencia y luego los requisitos funcionales y luego los no funcionales, ahora mismo justo tras la sección 4 hay requisitos, despúes va la tabla y despúes aparecen algunos requisitos repetidos, pero no todos lo que hay antes de la tabla.

R1 es no funcional, es una restricción.

R3, ¨Todos estos datos, a excepción el email y el nombre, podrán ser actualizados por el usuario.¨ esto es un no funcional a parte.

R5. "Podrá hacerlo desde el tablón de publicaciones o desde su perfil." esto es un no funcional a parte.

Revisad, porque lo mismo pasa en la mayoría de los requisitos.

**Comment by JavierSantiburcio** [comment]
Esta versión no era la versión final, pues faltaba revisar y añadir alguna cosa.
